language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

before_install:
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh
  - bash ./emp-readme/scripts/install_relic.sh
  - git clone https://github.com/emp-toolkit/emp-tool.git
  - cd emp-tool
  - git checkout 50c01ba99e5d257de05ef0e74ce6a0294a9ff471
  - cmake -DTHREADING=on .
  - sudo make install
  - cd ..
  - git clone https://github.com/emp-toolkit/emp-ot.git
  - cd emp-ot
  - git checkout 15fb731e528974bcfe5aa09c18bb16376e949283
  - cmake
  - sudo make install

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug . && make 
  - bin/test_pvc.cpp_exe aes alice & bin/test_pvc.cpp_exe aes bob
  - bin/test_pvc.cpp_exe sha1 alice & bin/test_pvc.cpp_exe sha1 bob
  - bin/test_pvc.cpp_exe mult alice & bin/test_pvc.cpp_exe mult bob
  - bin/test_pvc.cpp_exe sort alice & bin/test_pvc.cpp_exe sort bob
  - bin/test_pvc.cpp_exe ham alice & bin/test_pvc.cpp_exe ham bob
